<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

$string['pluginname'] = 'OriginalityAI Plagiarism Plugin';
$string['origai'] = 'OriginalityAI Plagiarism Plugin';
$string['enablemodule'] = 'Enable Plugin for {$a}';
$string['apiurl'] = 'OriginalityAI API Base URL';
$string['apikey'] = 'OriginalityAI API Key';
$string['studentdisclosuredefault']  ='All files uploaded will be submitted to a plagiarism detection service';
$string['studentdisclosure'] = 'Student Disclosure';
$string['studentdisclosure_help'] = 'This text will be displayed to all students on the file upload page.';
$string['useorigai'] ='Enable OriginalityAI';
$string['adminconfig'] = 'OriginalityAI Plagiarism Plugin Configuration';
$string['adminconfigsavesuccess'] = 'OriginalityAI Plagiarism Plugin Settings Saved';
$string['origaicoursesettings'] = 'OriginalityAI settings';
$string['origaienable'] = 'Enable OriginalityAI';
$string['plagiarismscan'] = 'Plagiarism Scan from Originality.AI';
$string['aiscan'] = 'AI Scan from OriginalityAI';
$string['reportpagetitle'] = 'Originality AI Scan Report';
$string['nopageaccess'] = 'Access Denied to this Page';
$string['matchpercentage'] = 'Match %: ';
$string['aipercentage'] = 'AI %: ';
$string['disabledformodule'] = 'OriginalityAI plugin is disabled for this module';
$string['apiurlrequired'] = 'Base URL of OriginalityAI API is required';
$string['apikeyrequired'] = 'Key of OriginalityAI API is required';
$string['apikeyhelp'] = 'If you do not have a API key, please <a target="_blank" href="https://originality.ai/?via=origai-moodle">click here to sign up for your own.</a>';
$string['status'] = "Status = ";
$string['successmsg'] = "Success";
$string['failmsg'] = "Fail";
$string['fleschscore'] = "Flesch Grade Level Score: ";
$string['fullreportlink'] = "Full Report Link";
$string['totalmatches'] = "Total Matches: ";
$string['matchinfo'] = "Match Information";
$string['score'] = "Score: ";
$string['phrase'] = "Phrase: ";
$string['website'] = "Website: ";
$string['classifierinfo'] = "Classifier Info: ";
$string['ai'] = "AI";
$string['original'] = "Original";
$string['fake'] = "Fake";
$string['real'] = "Real";
$string['privacy:metadata:plagiarism_origai_files'] = 'Information that links submission made on Moodle with the plagiarism results generated by OriginalityAI.';
$string['privacy:metadata:plagiarism_origai_plagscan:userid'] = 'The ID of the user who has made the submission.';
$string['privacy:metadata:plagiarism_origai_plagscan:totaltextscore'] = 'The total text score of the submission.';
$string['privacy:metadata:plagiarism_origai_plagscan:fleschgradelevel'] = 'The flesch grade level of the submission.';
$string['privacy:metadata:plagiarism_origai_plagscan:updatedtime'] = 'A timestamp indicating when the submission made by the user last modified';
$string['privacy:metadata:plagiarism_origai_client'] = 'In order to generate plagiarism report, submission data needs to be exchanged with OriginalityAI.';
$string['privacy:metadata:plagiarism_origai_client:submission_content'] = 'The submission content is sent to OriginalityAI for plagiarism report.';