<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

$string['accountconfig'] = 'Account Configuration';
$string['adminconfig'] = 'OriginalityAI Plagiarism Plugin Configuration';
$string['adminconfigdesc'] = 'The Originality.AI plugin offers a reliable and comprehensive solution for detecting both AI-generated content and plagiarism, helping educators and students ensure the authenticity of their work.<br>For setup instructions and usage details, please refer to <a target="_blank" href="https://docs.google.com/document/d/1KzYqrmDeGbTCO-JlO2zDSV-cXuVUyeTH03F0buzufyw/edit">our guide</a>.<br><br><br>';
$string['adminconfigsavesuccess'] = 'OriginalityAI Plagiarism Plugin Settings Saved';
$string['ai'] = "AI";
$string['aiModel'] = 'AI Model';
$string['aiModel_help'] = 'English for optimized English content or Multi-lang for support across multiple languages.';
$string['aipercentage'] = '{$a} Likely AI';
$string['airesulttitle'] = 'AI Check';
$string['aiscan'] = 'AI Scan from OriginalityAI';
$string['allowstudentreportaccess'] = 'Allow student access to view report';
$string['apiconnectionerror'] = 'API connection failed. Please verify account settings';
$string['apikey'] = 'OriginalityAI API Key';
$string['apikeyhelp'] = 'If you do not have a API key, please <a target="_blank" href="https://originality.ai/?via=origai-moodle">click here to sign up for your own.</a>';
$string['apikeyrequired'] = 'Key of OriginalityAI API is required';
$string['apiurl'] = 'OriginalityAI API Base URL';
$string['apiurlchanged'] = 'The API URL must be updated to {$a} for scans to run smoothly.';
$string['apiurlrequired'] = 'Base URL of OriginalityAI API is required';
$string['assign'] = 'Assignment';
$string['classifierinfo'] = "Classifier Info: ";
$string['defaultscanerror'] = "Scan failed";
$string['defaultsettings'] = "Default Settings";
$string['disabledformodule'] = 'OriginalityAI plugin is disabled for this module';
$string['enableautomatedscan'] = 'Enable automatic scanning on submission';
$string['enableautomatedscan_help'] = 'Automatically scans activity submissions after they\'re submitted. Uncheck to scan manually.';
$string['enablemodule'] = 'Enable Plugin for {$a}';
$string['failmsg'] = "Fail";
$string['fake'] = "Fake";
$string['fileattachmentnotsupported'] = 'File attachment type not supported';
$string['fleschscore'] = "Flesch Grade Level Score: ";
$string['fullreportlink'] = "Full Report Link";
$string['fullscreenview'] = "View in fullscreen";
$string['forum'] = 'Forum';
$string['humanpercentage'] = '{$a} Likely Original';
$string['inserterror'] = 'Error while trying to insert records to database';
$string['lite'] = 'English';
$string['matchinfo'] = "Match Information";
$string['matchpercentage'] = 'Match %: ';
$string['multilang'] = 'Multi-Lang';
$string['nopageaccess'] = 'Access Denied to this Page';
$string['origai'] = 'OriginalityAI Plagiarism Plugin';
$string['origaicoursesettings'] = 'OriginalityAI settings';
$string['origaienable'] = 'Enable OriginalityAI';
$string['original'] = "Original";
$string['originalityai'] = 'Originality.ai';
$string['phrase'] = "Phrase: ";
$string['plagiarismscan'] = 'Plagiarism Scan from Originality.AI';
$string['plagresulttitle'] = 'Match Score';
$string['pluginname'] = 'OriginalityAI Plagiarism Plugin';
$string['privacy:metadata:plagiarism_origai_client'] = 'In order to generate plagiarism report, submission data needs to be exchanged with OriginalityAI.';
$string['privacy:metadata:plagiarism_origai_client:submission_content'] = 'The submission content is sent to OriginalityAI for plagiarism report.';
$string['privacy:metadata:plagiarism_origai_files'] = 'Information that links submission made on Moodle with the plagiarism results generated by OriginalityAI.';
$string['privacy:metadata:plagiarism_origai_plagscan:fleschgradelevel'] = 'The flesch grade level of the submission.';
$string['privacy:metadata:plagiarism_origai_plagscan:totaltextscore'] = 'The total text score of the submission.';
$string['privacy:metadata:plagiarism_origai_plagscan:updatedtime'] = 'A timestamp indicating when the submission made by the user last modified';
$string['privacy:metadata:plagiarism_origai_plagscan:userid'] = 'The ID of the user who has made the submission.';
$string['quiz'] = 'Quiz';
$string['real'] = "Real";
$string['reportpagetitle'] = 'Originality AI Scan Report';
$string['retryscan'] = "Retry scan";
$string['runaicheck'] = 'Check AI';
$string['runplagiarismcheck'] = 'Check Plagiarism';
$string['scanfailed'] = "Scan failed";
$string['scaninprogress'] = "Scan is in progress";
$string['scanqueued'] = "Scan queued";
$string['scanqueuednotification'] = "Scan successfully queued. Processing will begin shortly.";
$string['scanreportfailed'] = "Unable to get scan report";
$string['score'] = "Score: ";
$string['sendqueuedsubmissionstaskname'] = "OriginalityAI plugin - handle queued files";
$string['standard'] = 'Standard';
$string['status'] = "Status = ";
$string['studentdisclosure'] = 'Student Disclosure';
$string['studentdisclosure_help'] = 'This text will be displayed to all students on the file upload page.';
$string['studentdisclosuredefault']  = 'All content submitted will be passed for plagiarism and AI detection';
$string['successmsg'] = "Success";
$string['textextractionfailed'] = 'Failed to extract text';
$string['totalmatches'] = "Total Matches: ";
$string['updateerror'] = 'Error while trying to update records in database';
$string['useorigai'] = 'Enable OriginalityAI';
$string['website'] = "Website: ";
